// Generates src/embedded-app.ts (bundled frontend + html + css as strings)
// so `bun build --compile` can produce a single self-contained executable.
// Run before compiling: bun run scripts/embed.ts

import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");

const result = await Bun.build({
  entrypoints: [join(ROOT, "web", "main.ts")],
  target: "browser",
  minify: true,
});
if (!result.success) {
  console.error(result.logs);
  process.exit(1);
}
const appJs = await result.outputs[0]!.text();
const html = await Bun.file(join(ROOT, "web", "index.html")).text();
const css = await Bun.file(join(ROOT, "web", "style.css")).text();

const out = `// GENERATED by scripts/embed.ts — do not edit or commit.
// Used only by 'bun run compile' to bake the frontend into a single executable.
export const APP_JS = ${JSON.stringify(appJs)};
export const APP_HTML = ${JSON.stringify(html)};
export const APP_CSS = ${JSON.stringify(css)};
`;
await Bun.write(join(ROOT, "src", "embedded-app.ts"), out);
console.log(`embedded-app.ts written (${(appJs.length / 1024).toFixed(0)} KB js, ${(css.length / 1024).toFixed(0)} KB css)`);
